
import React, { 
    LayoutDashboard, 
    CandlestickChart, 
    Newspaper, 
    BrainCircuit, 
    Settings, 
    Search, 
    Bell, 
    TrendingUp, 
    TrendingDown, 
    BarChart,
    BarChart3,
    Plus,
    Layers,
    ArrowRight,
    Activity,
    Zap,
    Filter,
    Download,
    Play,
    Pause,
    AlertTriangle,
    FileText,
    Sliders,
    Eye,
    List,
    Flame,
    Gauge,
    Trophy,
    PieChart,
    Wallet,
    GripVertical,
    Bot,
    Maximize2,
    Share2,
    Camera,
    Crosshair,
    PenTool,
    Eraser,
    MoreHorizontal,
    ChevronDown,
    Clock,
    Unlock,
    Lock,
    RefreshCw,
    Target,
    Briefcase,
    Code2,
    Terminal,
    GitBranch,
    Cpu,
    History,
    CheckCircle2,
    XCircle,
    Copy,
    Save,
    Mic,
    Send,
    MessageSquare,
    Sparkles,
    Command,
    Grid,
    // Add Compass icon to imports
    Compass
  } from 'lucide-react';
  
  export const Icons = {
    Dashboard: LayoutDashboard,
    Market: BarChart3,
    BarChart: BarChart,
    Plus: Plus,
    Trade: CandlestickChart,
    News: Newspaper,
    AI: BrainCircuit,
    Settings: Settings,
    Search: Search,
    Bell: Bell,
    Up: TrendingUp,
    Down: TrendingDown,
    Layers: Layers,
    ArrowRight: ArrowRight,
    Activity: Activity,
    Zap: Zap,
    Filter: Filter,
    Download: Download,
    Play: Play,
    Pause: Pause,
    Alert: AlertTriangle,
    File: FileText,
    Sliders: Sliders,
    Eye: Eye,
    List: List,
    Flame: Flame,
    Gauge: Gauge,
    Trophy: Trophy,
    Pie: PieChart,
    Wallet: Wallet,
    Drag: GripVertical,
    Robot: Bot,
    Maximize: Maximize2,
    Share: Share2,
    Camera: Camera,
    Crosshair: Crosshair,
    Pen: PenTool,
    Eraser: Eraser,
    More: MoreHorizontal,
    ChevronDown: ChevronDown,
    Clock: Clock,
    Unlock: Unlock,
    Lock: Lock,
    Refresh: RefreshCw,
    Target: Target,
    Briefcase: Briefcase,
    Code: Code2,
    Terminal: Terminal,
    Git: GitBranch,
    Cpu: Cpu,
    History: History,
    CheckCircle: CheckCircle2,
    XCircle: XCircle,
    Copy: Copy,
    Save: Save,
    Mic: Mic,
    Send: Send,
    MessageSquare: MessageSquare,
    Sparkles: Sparkles,
    Command: Command,
    Grid: Grid,
    // Map Compass icon to the Icons object
    Compass: Compass
  };
